# Generated by Django 4.2.7 on 2023-11-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dmr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreading",
            name="flow",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
