# Generated by Django 4.2.7 on 2023-11-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dmr", "0003_alter_dailyreading_flow_alter_dailyreading_gallons_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outfall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="dailyreading",
            name="outfall",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="dmr.outfall"
            ),
        ),
    ]
